# Generated by Django 3.0.5 on 2020-04-01 13:03

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Questions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qustion', models.CharField(max_length=100)),
                ('option1', models.CharField(max_length=50)),
                ('option2', models.CharField(max_length=50)),
                ('option3', models.CharField(max_length=50)),
                ('option4', models.CharField(max_length=50)),
                ('isActive', models.BooleanField(default=False)),
                ('createdDate', models.DateTimeField(auto_now_add=True)),
                ('updatedDate', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Register',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=40, null=True)),
                ('userId', models.IntegerField(blank=True, null=True)),
                ('role', models.IntegerField()),
                ('isActive', models.BooleanField(default=False)),
                ('createdDate', models.DateTimeField(auto_now_add=True)),
                ('updatedDate', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserAnswer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('QuID', models.IntegerField(blank=True, null=True)),
                ('userAns', models.IntegerField()),
                ('userid', models.IntegerField(blank=True, null=True)),
                ('isActive', models.BooleanField(default=False)),
                ('createdDate', models.DateTimeField(auto_now_add=True)),
                ('updatedDate', models.DateTimeField(auto_now=True)),
                ('Questions', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.fields.Empty, to='Website.Questions')),
                ('Register', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Website.Register')),
            ],
        ),
    ]
